# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7731ba3a67db45cd5e6a816d0b134b75"
name = "mern-crud-app"
handle = "mern-crud-app"
application_url = "https://nottingham-wondering-focused-connecticut.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://nottingham-wondering-focused-connecticut.trycloudflare.com/auth/callback", "https://nottingham-wondering-focused-connecticut.trycloudflare.com/auth/shopify/callback", "https://nottingham-wondering-focused-connecticut.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
